### ISSUE TITLE
新建插件后插件面板没有跳到新插件

### ISSUE THREAD

**Issue by dhshen** [MossTeam/HelloWeb#7]
需要手动选择进入新建的插件页面，用户体验不好，点击插件信息弹框中的“确定”按钮后很懵，感觉不见了，需要去左边栏里面找自己刚创建插件的名称，需要点反应时间。

![](https://i.loli.net/2018/09/25/5ba9f7bf07a37.png)

**Comment by SheldonLaw** [comment]
Fixed.
