### ISSUE TITLE
插件的重启功能什么意思

### ISSUE THREAD

**Issue by dhshen** [MossTeam/HelloWeb#8]
点击重启，
操作预期：
1.修改了package.json中的author，期待界面会更新。——没有
2.工具重启。——没有

整块面板缺乏指引或说明文档

**Comment by SheldonLaw** [comment]
bug: 插件逻辑上已经完成了关闭和重新启动，但是视图没有更新。

**Comment by SheldonLaw** [comment]
Fixed.
